spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sns?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: root

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        # Hibernate 6 ?? ???? ???
        type:
          descriptor:
            sql:
              BasicBinder: TRACE

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

jwt:
  secret-key: fastcampus.sns-application.secret-key
  token:
    # 30? (24 * 60 * 60 * 30) * 1000 (ms)
    expired-time-ms: 2592000000